### PR TITLE
add Mathematica example for schmudgen SDP problems

### PR DESCRIPTION
**Pull request by jaehlee**

### CODE REVIEW

**Comment by davidsd** [comment]
Hi, thanks for this! Does "Schmudgen" refer to positivity conditions on different intervals (as opposed to the default [0,infinity))? Would you mind adding some comments in the files describing what they're demonstrating and how they work?

**Comment by davidsd** [comment]
Another comment: instead of duplicating a lot of function definitions in SDPBSchmudgen, it would be better to import SDPB.m and then add some new functions. This would make both files easier to understand and maintain.

**Comment by jaehlee** [comment]
Yes, Ethan and I have found a way to make positivity conditions on different intervals. I didn't meant to request merging the current version to the original repo yet (Trying to learn how to properly use Github).

There are some changes for src files which I haven't commit yet. Current development version can deal with one extra interval and trying to generalize to general case.  I will make proper pull request after changes(including suggested ones) are made. You can close the current request.

**Comment by davidsd** [comment]
Ok, cool. Looking forward to the final pull request!

**Pull request closed without merging**
